# docker-compose.yml
version: '3'
    
services:
  app:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    restart: always
    volumes:
      - "/dev/serial0:/dev/serial0"
    ports:
      - 8080:8080